- docs/CODEOWNERS.md
Initialize code owners of the project
@bpetetot 
@frinyvonnick 
@kefranabg 
@charlyx 
@mfrachet
@christopherkade
Closes #13
> :busts_in_silhouette: adding code owners

- .circleci/config.yml
- netlify.toml
- package.json
- yarn.lock
This pull request add CircleCI and Netlify.
For the moment a  preview is deployed for each pull-request. All build passed on master is published on zenika-open-source-insight.netlify.com
Note : I need that PR to be merged in order to configure CircleCI.
Closes #10
> :construction_worker: add CircleCI and Netlify

- .circleci/config.yml
Sorry guys, I don't know what happen. I made a mistake with my last PR. The deploy command was wrong. 
This fix the CI.
> Fix wrong deploy command

- src/data/stats.json
> 🍱 Add stats file

- src/components/Footer/Footer.js
In order to be complient with our netlify contract, we must display netlify link
> :lipstick: Add netlify link

- README.md
- package.json
Small README improvements 😃 
README generated with [https://github.com/kefranabg/readme-md-generator](https://github.com/kefranabg/readme-md-generator)
> :pencil: Improve README content

- src/components/Stats/TopProjects/Project/Project.js
> 💄 update top projects link placement

- src/components/NewProjects/ProjectCard/ProjectCard.css
- src/components/NewProjects/ProjectCard/ProjectCard.js
update project title tag to h2 for a11y #50
> 💄 Update highlighted projects font size

- src/components/NewProjects/ProjectCard/ProjectCard.css
- src/components/Stats/People/People.css
- src/components/Stats/TopProjects/TopProjects.css
- src/components/layout.css
> :lipstick: Underline link only on mouse over

- package.json
- src/components/Metrics/Metric/Metric.css
- src/components/Metrics/Metric/Metric.js
- yarn.lock
> ➖ Remove react-countup

- gatsby-config.js
> :sparkles: set correct manifest

- gatsby-config.js
- package.json
- yarn.lock
> :chart_with_upwards_trend: Add Google Analytics

- gatsby-config.js
- static/cookie.js
> :bug: fixing cookies consent

- static/hacktoberfest.json
Hello 👋 
Here is my Github handle to participate to Hacktoberfest 😄
> ✨  add ebriand handle

- src/pages/hacktoberfest.jsx
Hey 👋 
I propose with this PR to change the hacktoberfest leaderboard headers, WDYT?
> 💄 changed wording for leaderboard headers

- static/hacktoberfest.json
> add mathieumure handle for hacktoberfest

- static/hacktoberfest.json
> Add mchoraine Hacktoberfest Contributor

- static/hacktoberfest.json
First time that I fork a project to make PR !
> Add me (Jules) to Zenika challenge

- static/hacktoberfest.json
Just adding my github username to the `hacktoberfest.json` file.
> Add glefloch in hacktoberfest.json

- static/hacktoberfest.json
> Add rlemaire, Paris to hacktoberfest.json

- static/hacktoberfest.json
Added Olivier Perez, Louis Tournaire, Julie Nguyen, Martin Piegay and Ilyes Semlali
> Added Lyon hacktoberfest team!

- static/hacktoberfest.json
I want the pretty tshirt ! Happy Hacktoberfest, folks :heart: :tada:
> :pencil: Add mcampourcy to hacktoberfest file

- static/hacktoberfest.json
Et je vous souhaite un bon hacktoberfest à tous ! :)
> Add nbrdx to Zenika open source contributors

- static/hacktoberfest.json
> Add my participation as an opensource helper!

- static/hacktoberfest.json
> Add my name

- src/pages/hacktoberfest.jsx
If there are 2 ex-aequo in the first place, the next one is ranked third, not second.
> Update the Hacktoberfest rankings.

- static/hacktoberfest.json
> :memo: Add cycy-realbeats

- gatsby-config.js
Hi 😀
It's my first time opening a PR in this project !
Happy Hacktoberfest 🎉
> :zap: Add Web App Manifest and support for an offline experience

- static/hacktoberfest.json
> :sparkles: update hacktoberfest.json: add Maël N.

- static/hacktoberfest.json
Adding myself on the leaderboard ✨
> :sparkles: add bgauduch user to the leaderboard

- static/hacktoberfest.json
> add pyaillet 🤓

- static/hacktoberfest.json
add myself to hacktoberfest leaderboard :smiley:
> hacktoberfest: alocquet

- static/hacktoberfest.json
Enfin je me décide à participer 😄
> Ajout du nom et localisation

- static/hacktoberfest.json
Add myself to hacktoberfest.json 🎊
> add Gosunet to hacktoberfest.json

- static/hacktoberfest.json
> Ajout de Charlotte-29 dans le fichier des participants

- static/hacktoberfest.json
> add guillaumeLamanda to contributors

- static/hacktoberfest.json
> Ajout Helliz !

- static/hacktoberfest.json
See [CAMEL-15772: camel-pulsar readCompacted support](https://github.com/apache/camel/pull/4535)
> Add camel pulsar contribution

- src/components/Blog/Blog.css
- src/components/Metrics/Metric/Metric.css
- src/components/NewProjects/ProjectCard/ProjectCard.css
- src/components/Stats/TopProjects/TopProjects.css
- src/components/layout.css
- src/templates/BlogPost.css
Hey 👋 
I changed the red color used in the website to a new red to comply with the new Zenika branding guidelines. Do I have to update it elsewhere ? 🤔
> :lipstick: change color to match new Zenika branding

- static/hacktoberfest.json
> Add pyaillet ;)

- static/hacktoberfest.json
> Add Jules H.

- README.md
- src/components/Hacktoberfest/Hacktoberfest.jsx
- src/components/Hacktoberfest/useHacktoberfest.js
- src/pages/hacktoberfest.jsx
- static/hacktoberfest-new.json
Let's go to integrate MR GitLab on the oss.zenika.com (issue #311 ).
Steps : 
- 1️⃣  add a template of new hacktoberfest.json ✅ 
- 2️⃣ as the structure of the hactoberfest.json evolved, changes have to be done
> 🚀  Add MR GitLab on the leaderboard

- content/white-paper/getting-started/index.md
- content/white-paper/preparing-your-project-being-open-sourced/index.md
- content/white-paper/promotion/index.md
- content/white-paper/understanding-software-licenses/index.md
- gatsby-browser.js
- gatsby-node.js
Probablement pas la bonne solution mais semble faire le taf. A voir le comportement des GH dans la PR.
Le changement dans gatsby-node viens d'une des actions de la migration v4-5.
J'ai supprimé un fichier qui était marqué à supprimer si non utilisé. :D
> fix: quick fix adding trailing / after gatsby 5 hardcore upgrade :D

- static/hacktoberfest.json
> Add me (Antoine Ceol)

- static/hacktoberfest.json
> Add Guillaume Le Floch as contributor

- src/components/layout.jsx
> 💥 Hide the Hacktoberfest banner

- static/hacktoberfest.json
> Ajout Valentin Montreal

- static/hacktoberfest.json
> ✨ Add yannbertrand
